# Generated by Django 3.1 on 2020-12-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_person_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, default='image1.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20000, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=20000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.person')),
            ],
        ),
    ]
