# Generated by Django 3.1 on 2020-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_userperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, default='image1.jpg', max_length=20000, null=True),
        ),
    ]
