# Generated by Django 3.1 on 2020-12-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201215_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(default=0)),
                ('content', models.CharField(blank=True, max_length=20000, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=20000, null=True)),
                ('userPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.person')),
            ],
        ),
    ]
