# Generated by Django 3.1 on 2020-12-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201215_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='blog.person')),
                ('u2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed', to='blog.person')),
            ],
        ),
    ]
